1C-Company/v8-code-style

bundles/com.e1c.v8codestyle.md/META-INF/MANIFEST.MF, bundles/com.e1c.v8codestyle.md/plugin.xml, bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClient.java, bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClientServer.java, bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameGlobal.java, bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleType.java, bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ConfigurationDataLock.java, bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdObjectNameLength.java, bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdObjectNameWithoutSuffix.java, bundles/com.e1c.v8codestyle/META-INF/MANIFEST.MF, bundles/com.e1c.v8codestyle/plugin.xml, tests/com.e1c.v8codestyle.md.itests/META-INF/MANIFEST.MF, tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/itests/CommonModuleNameClientServerTest.java, tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/itests/CommonModuleNameClientTest.java, tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/itests/CommonModuleNameGlobalTest.java, tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/itests/CommonModuleTypeTest.java, tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/itests/ConfigurationDataLockTest.java, tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/itests/MdObjectNameLengthTest.java
Схема именования соответствует планируемой релизной схеме механизма проверок.
=> #6 Адаптация к новой схеме именования API проверок

.github/workflows/ci-build.yml
Удаление ненужного перед сборкой для освобождения места на диске.
Изменение версии скрипта для кеширования, так как в нём есть оптимизация работы с местом.
=> Увеличение свободного места при сборке

bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClient.java, bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClientServer.java, bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameGlobal.java
Отключено форматирование в методе configureCheck для тестов common-module-name-*
=> Отключено форматирование в методе configureCheck

tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/itests/CommonModuleNameClientTest.java, tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/itests/CommonModuleNameGlobalTest.java
Кто-то тесты делал копипастом. И после копипаста не всё заменил в тексте тестов.
=> После копипастинга не поменяли тесты

bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdListObjectPresentationCheck.java
=> #798 Учет регистров сведений, подчиненных регистратору

bundles/com.e1c.v8codestyle.bsl/markdown/change-and-validate-instead-of-around.md, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ChangeAndValidateInsteadOfAroundCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
Вместо ChangeAndValidate почему-то написал ChangeAndControl
=> Опечатка в названии аннотации

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ChangeAndValidateInsteadOfAroundCheck.java
Поиск Invocation, а не произвольного StaticFeatureAccess
=> Поиск вызовов методов, а не произвольного StaticFeatureAccess

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/InvocationParamIntersectionCheck.java, tests/com.e1c.v8codestyle.bsl.itests/resources/strict/invocation-parameter-type-intersect-with-default.bsl, tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/strict/check/itests/CommonModuleStrictTypesTest.java
=> #819 Учет пустого выражения для параметров по умолчанию

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/AbstractTypeCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/SimpleStatementTypeCheck.java, tests/com.e1c.v8codestyle.bsl.itests/resources/strict/statement-type-change-with-doc-comment.bsl, tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/strict/check/itests/CommonModuleStrictTypesTest.java
=> #813 учет типов в строке для локальных переменных

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/EventHandlerBooleanParamCheck.java
- Исправлено падение при работе проверки
Общее:
Closes #850
=> #850 Проверка существования наборов параметров

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/EventDataExchangeLoadCheck.java
- Исправлена проверка - события проверяются в расширении по аннотации в которой указано процедура обработчик события ПриЗаписи, ПередЗаписью и ПередУдалением
Общее:
Closes #457
=> #457 Проверка ОбменДанными.Загрузка проверяет расширения

docs/contributing/code_style.md
Исправлены опечатки, подправлено форматирование.
=> Исправление опечаток и форматирования.

docs/contributing/environment.md
=> Исправлены опечатки

bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/CommonModuleTypes.java
- Исправлены настройки типа модуля для глобального
Общее:
Closes #924
=> #924 Исправление типа глобального клиентского модуля

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java, tests/com.e1c.v8codestyle.bsl.itests/resources/query-in-loop.bsl, tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/QueryInLoopCheckTest.java
Исправлено ложное срабатывание диагностики, если функция с циклом передается в качестве параметра в цикл Для Каждого Из
Общее:
Closes #905 
@1C-Company @marmyshev прошу сделать аудит
=> #905 Ошибочное срабатывание на параметре цикла Для Каждого Из

.github/workflows/build.yml
- Выключено использование параллельной сборки
Общее:
Closes #??
=> Отключение параллельной сборки, т.к. лог превращается в кашу

docs/contributing/issue.md
Исправлены битые ссылки в документации.
=> Исправление битых ссылок

bundles/com.e1c.v8codestyle.bsl/plugin.xml
Временно отключены проверки в плагине
=> 980-disable-undefined-checks: Временное отключение проверок undefined*

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/comment/check/ExportFunctionReturnSectionCheck.java
- Исправлено ложное срабатывание проверки: doc-comment-export-function-return-section
Общее:
Closes #948
=> #948 Исправлено ложное срабатывание проверки:

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/comment/check/AbstractDocCommentTypeCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/comment/check/RefLinkPartCheck.java
- Опишите изменения функциональности
- Реализованные проверки кода и метаданных
Общее:
Closes #984
=> #984 Исправлена валидация ссылки

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/AbstractTypeCheck.java
- Более точное пересечение типов
Общее:
Closes #987
=> #987 Более точное пересечение типов

bundles/com.e1c.v8codestyle.bsl/plugin.xml, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/EventHandlerBooleanParamCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/LockOutOfTryCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleUnusedLocalVariableCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/NotifyDescriptionToServerProcedureCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/comment/check/ExportFunctionReturnSectionCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/comment/check/FieldDefinitionTypeWithLinkRefCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/comment/check/FunctionReturnSectionCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/comment/check/RefLinkPartCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/comment/check/TypeDefinitionCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/FunctionCtorReturnSectionCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/InvocationParamIntersectionCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/BslPlugin.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/ExternalDependenciesModule.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/ServiceModule.java, bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/internal/ql/ExternalDependenciesModule.java, bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/VirtualTableFiltersCheck.java
- Исправление инжектинга сервисов приводящее к дублированию инстансов, которые должны быть Singltone
- Унификация инжектинга сервисов Xtext для которых нет интерфейса
Общее:
Closes #1010
=> #1010 Исправление и рефакторинг инжектинга сервисов Xtext

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleEmptyMethodCheck.java, tests/com.e1c.v8codestyle.bsl.itests/resources/module-empty-method.bsl, tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ModuleEmptyMethodCheckTest.java
поправил логику работы проверки, теперь комментарии за методом не учитываются
Closes #1007
=> Неправильно валидируется пустой метод с комментарием #1007

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/FormModuleMissingPragmaCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/comment/check/DocCommentUseMinusCheck.java
Понизил уровень ошибки для проверок с кодами - 
Например: Closes #1014
=> Понижение критичности для ошибок с кодами  b6bdf45 "doc-comment-use-minus", "form-module-missing-pragma" #1014

bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefUseAlwaysFlagDisabledCheck.java
form-list-ref-use-always-flag-disabled
Исправлена ошибка приведения типа
=> 1041: ClassCastException в проверке

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
- Исправление NPE
Общее:
Closes #??
=> Исправление npe

bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
- Удалены лишние скобки
Общее:
Closes #??
=> Исправление лишних скобок

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureEventRegionsCheck.java
- Добавлен ифльтр по типу модуля
Общее:
Closes #??
=> Добавлен ифльтр по типу модуля

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureEventFormRegionsCheck.java
- Исправление на регистронезависимое сравнение и другие мелкие правки
Общее:
Closes #??
=> Исправление на регистронезависимое сравнение

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
- Добавлена фильтрация модулей для проверки
Общее:
Closes #??
=> Добавлена фильтрация модулей для проверки

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureEventFormRegionsCheck.java
- Исправление NPE
Общее:
Closes #??
=> Исправлена NPE

CHANGELOG.md, bundles/com.e1c.v8codestyle.bsl/META-INF/MANIFEST.MF, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/AbstractTypeCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/InternalTypeNameRegistry.java, tests/com.e1c.v8codestyle.bsl.itests/resources/strict/invocation-parameter-type-intersect-catalog-object.bsl, tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/strict/check/itests/InvocationParamIntersectionCheckTest.java, tests/com.e1c.v8codestyle.bsl.itests/workspace/CatalogModules/.project, tests/com.e1c.v8codestyle.bsl.itests/workspace/CatalogModules/.settings/org.eclipse.core.resources.prefs, tests/com.e1c.v8codestyle.bsl.itests/workspace/CatalogModules/DT-INF/PROJECT.PMF, tests/com.e1c.v8codestyle.bsl.itests/workspace/CatalogModules/src/Catalogs/TestCatalog/TestCatalog.mdo, tests/com.e1c.v8codestyle.bsl.itests/workspace/CatalogModules/src/Configuration/CommandInterface.cmi, tests/com.e1c.v8codestyle.bsl.itests/workspace/CatalogModules/src/Configuration/Configuration.mdo, tests/com.e1c.v8codestyle.bsl.itests/workspace/CatalogModules/src/Configuration/MainSectionCommandInterface.cmi
- Исправление пересечения родительских типов ОМД 
- Соответствия типов вынесены в отдельный реестр
Общее:
Closes #1138
=> Исправление пересечения родительских типов ОМД #1138

tests/com.e1c.v8codestyle.bsl.itests/workspace/CommonModuleNamedSelfReferenceCheck/DT-INF/PROJECT.PMF, tests/com.e1c.v8codestyle.bsl.itests/workspace/FormSelfReferenceOutdatedCheck/DT-INF/PROJECT.PMF, tests/com.e1c.v8codestyle.bsl.itests/workspace/ManagerModuleNamedSelfReferenceCheck/DT-INF/PROJECT.PMF, tests/com.e1c.v8codestyle.bsl.itests/workspace/SelfReferenceCheck/DT-INF/PROJECT.PMF, tests/com.e1c.v8codestyle.bsl.itests/workspace/ServerExecutionSafeModeCheck/DT-INF/PROJECT.PMF
- Версия тестовых проектов понижена до 8.3.19
Общее:
Closes #??
=> Версия тестовых проектов 8.3.19

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureEventFormRegionsCheck.java
- Исправлена ошибка проверки лишних методов в области обработчиков табличной части
Общее:
Closes #??
=> Исправление ошибки

tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ExtensionMethodPrefixCheckTest.java
- Рефакторинг теста
Общее:
Closes #??
=> Рефакторинг теста

bundles/com.e1c.v8codestyle.bsl/META-INF/MANIFEST.MF, tests/com.e1c.v8codestyle.right.itests/META-INF/MANIFEST.MF, tests/com.e1c.v8codestyle.right.itests/src/com/e1c/v8codestyle/internal/right/itests/CheckExternalDependenciesModule.java, tests/com.e1c.v8codestyle.right.itests/src/com/e1c/v8codestyle/internal/right/itests/CheckRights.java
=> fix manifest versions & service dependences

bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/messages_ru.properties
- Опишите изменения функциональности
- Реализованные проверки кода и метаданных
Общее:
Closes #??
=> Опечатка замечания CommonModuleType_message

tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/AbstractSingleModuleTestBase.java, tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/fix/itests/ConsecutiveEmptyLinesFixTest.java, tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/strict/check/itests/CommonModuleStrictTypesTest.java
- Временный обходи проблемы
Общее:
Closes #??
=> Временное исправление для обхода проблемы в ЕДТ

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
- Для модуля BSL check поправлены ошибки в messages_ru.properties
Общее:
Closes #1269 
@1C-Company @marmyshev прошу сделать аудит
=> #1269 Исправлены сообщения проверок в messages_ru.properties

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/FunctionCtorReturnSectionCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/InvocationParamIntersectionCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/SimpleStatementTypeCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/TypedValueAddingToUntypedCollectionCheck.java
Поправлены возможные NPE при получении имени типа через McoreUtil.getTypeName
=> G5V8DT-23259 Падение NPE в коде расчета типов

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CodeAfterAsyncCallCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportMethodInCommandFormModuleCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/NotifyDescriptionToServerProcedureCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
Внес правки в проверки связи с тем, что тип описание оповещения изменил свое имя, начиная с версии 8.3.22
=> EPI-978 Проблемы с типом ОписаниеОповещения

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/PublicMethodCachingCheck.java
- Исправлена ошибка NPE
Общее:
Closes #1323
=> #1323 Исправление ошибки NPE

tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/IsInRoleMethodRoleExistCheckTest.java
Из импорта удалены ненужные классы.
- Из импорта IsInRoleMethodRoleExistCheckTest.class удалены ненужные классы.
Общее:
Closes #??
=> Исправлен импорт в классе проверки IsInRoleMethodRoleExistCheckTest

bundles/com.e1c.v8codestyle.autosort/META-INF/MANIFEST.MF, bundles/com.e1c.v8codestyle.autosort/src/com/e1c/v8codestyle/internal/autosort/ExternalDependenciesModule.java
исправлено падение теста https://github.com/1C-Company/v8-code-style/actions/runs/5154310909/jobs/9821765350
=> G5V8DT-23868

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
Исправлена ошибка в сообщении для проверки
MethodOptionalParameterBeforeRequiredCheck.
- Поправлен текст сообщений для русской локализации.
Общее:
Closes #1351 
@1C-Company @marmyshev прошу сделать аудит
=> #1351 Исправлена ошибка в сообщении для проверки MethodOptionalParameterBeforeRequiredCheck

bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/bsl/ui/qfix/OpenBslDocCommentViewFix.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportProcedureMissingCommentCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureTopRegionCheck.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/TypedValueAddingToUntypedCollectionCheck.java, bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleRightSetCheck.java, tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/RedundantExportMethodCheckTest.java
В нескольких "проверках" были добавлены проверки на null
=> Feature/1378: Добавлены проверки на null

bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/messages.properties, bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/messages_ru.properties
- Исправление ошибки
Общее:
Closes #??
=> Исправление файлов свойств

tests/com.e1c.v8codestyle.bsl.itests/resources/doc-comment-ref-link.bsl
Исправлен ресурс для теста. В ресурсе неправильно описаны ссылки
Общее:
Closes #1376
=>  Падает тест RefLinkPartCheckTest #1376 

bundles/com.e1c.v8codestyle.autosort.ui/src/com/e1c/v8codestyle/autosort/ui/properties/Messages.java, bundles/com.e1c.v8codestyle.autosort.ui/src/com/e1c/v8codestyle/internal/autosort/ui/Messages.java, bundles/com.e1c.v8codestyle.autosort/src/com/e1c/v8codestyle/internal/autosort/Messages.java, bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/bsl/ui/qfix/Messages.java, bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/internal/bsl/ui/handlers/Messages.java, bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/internal/bsl/ui/preferences/Messages.java, bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/internal/bsl/ui/properties/Messages.java, bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/internal/bsl/ui/views/Messages.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/Messages.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/comment/check/Messages.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/qfix/Messages.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/Messages.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/fix/Messages.java, bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/Messages.java, bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/Messages.java, bundles/com.e1c.v8codestyle.md.ui/src/com/e1c/v8codestyle/md/ui/Messages.java, bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/Messages.java, bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/Messages.java, bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/Messages.java, bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/Messages.java, bundles/com.e1c.v8codestyle.ui/src/com/e1c/v8codestyle/internal/ui/Messages.java, bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/internal/Messages.java
- Упрощение файла локализации при копировании или рефакторинге пакетов
Общее:
Closes #??
=> Рефакторинг класса локализации

bundles/com.e1c.v8codestyle.bsl.ui/plugin.xml, bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/internal/bsl/ui/services/BslModuleRegionsInfoService.java, tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/SelfReferenceCheckTest.java
Исправил зависание при добавление обработчика для элементов форм вложенных в таблицу, поправил логику генерации Областей модуля при добавлении обработчика, теперь область генерируется только при включенном свойстве проекта "Автоматически создавать структуру модуля"
=> G5V8DT-24674 Взводится признак наличия изменений при переходе к обработчику формы

bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/DataCompositionConditionalAppearanceUseCheck.java
- Опишите изменения функциональности
- Реализованные проверки кода и метаданных
Общее:
Closes #??
=> 1443 data composition conditional appearance use

bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/TempTableHasIndex.java
правки после выполнения задачи по поддержки Дополнительные возможности по работе с временными таблицами в версии платформы 8.3.25
=> G5V8DT-24657 Дополнительные возможности по работе с временными таблицами.

bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CodeAfterAsyncCallCheck.java
Убрать отладочный код.
Общее:
Closes #??
=> G5V8DT-25134 Падают тесты CodeAfterAsyncCallCheckTest

bundles/com.e1c.v8codestyle.autosort/META-INF/MANIFEST.MF, bundles/com.e1c.v8codestyle.bsl.ui/META-INF/MANIFEST.MF, bundles/com.e1c.v8codestyle.bsl/META-INF/MANIFEST.MF, bundles/com.e1c.v8codestyle.form/META-INF/MANIFEST.MF, bundles/com.e1c.v8codestyle.md/META-INF/MANIFEST.MF, bundles/com.e1c.v8codestyle.ql/META-INF/MANIFEST.MF, bundles/com.e1c.v8codestyle.right/META-INF/MANIFEST.MF, bundles/com.e1c.v8codestyle/META-INF/MANIFEST.MF
=> Поднятие версии BM core
